# Generated by Django 3.2.6 on 2023-08-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertrating',
            name='judging',
            field=models.CharField(default=None, max_length=500, verbose_name='judging'),
        ),
        migrations.AddField(
            model_name='pastarating',
            name='judging',
            field=models.CharField(default=None, max_length=500, verbose_name='judging'),
        ),
        migrations.AddField(
            model_name='saladrating',
            name='judging',
            field=models.CharField(default=None, max_length=500, verbose_name='judging'),
        ),
        migrations.AddField(
            model_name='snacksrating',
            name='judging',
            field=models.CharField(default=None, max_length=500, verbose_name='judging'),
        ),
    ]
