# Generated by Django 3.2.6 on 2023-08-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='FK_13',
            field=models.CharField(choices=[(None, ''), ('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=300, verbose_name='FK_13'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='FK_14',
            field=models.CharField(choices=[(None, ''), ('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=300, verbose_name='FK_14'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='FK_15',
            field=models.CharField(choices=[(None, ''), ('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=300, verbose_name='FK_15'),
        ),
    ]
