# Generated by Django 3.2.6 on 2023-08-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('image_link', models.CharField(max_length=500)),
                ('rating', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'salad',
                'db_table': 'Salad',
                'ordering': ['id'],
            },
        ),
    ]
