# Generated by Django 3.2.6 on 2023-08-30 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_quality', '0002_auto_20230825_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=1000)),
                ('image_link', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'recipes',
                'db_table': 'recipes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='recipesRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[(None, ''), ('1', '1 Very Unattractive'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7 Very Attractive')], default=None, max_length=500, verbose_name='rating')),
                ('judging', models.CharField(default=None, max_length=500, verbose_name='judging')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_quality.personal_info')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_quality.dissert')),
            ],
            options={
                'verbose_name': 'Ratings',
                'db_table': 'recipesRatings',
                'ordering': ['id'],
            },
        ),
    ]
