# Generated by Django 3.2.6 on 2023-08-03 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_quality', '0002_salad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salad',
            name='rating',
        ),
        migrations.CreateModel(
            name='SaladRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('image_link', models.CharField(max_length=500)),
                ('rating', models.CharField(max_length=500)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_quality.personal_info')),
            ],
            options={
                'verbose_name': 'saladrating',
                'db_table': 'Saladrating',
                'ordering': ['id'],
            },
        ),
    ]
