# Generated by Django 3.2.6 on 2023-08-30 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_quality', '0003_recipes_recipesrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesrating',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_quality.recipes'),
        ),
    ]
