# Generated by Django 3.2.6 on 2023-08-03 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_quality', '0003_auto_20230803_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='saladrating',
            name='salad',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='image_quality.salad'),
            preserve_default=False,
        ),
    ]
