# Generated by Django 3.2.6 on 2023-08-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_quality', '0004_saladrating_salad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saladrating',
            name='Name',
        ),
    ]
