# Generated by Django 3.2.6 on 2023-08-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_quality', '0005_alter_recipesrating_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='FK_13',
        ),
    ]
