# Generated by Django 3.2.6 on 2023-09-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_quality', '0008_auto_20230905_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghs_fk',
            name='CS_15',
        ),
    ]
